









Traceback (most recent call last):
  File "/home/hongyuan/trader/backtest.py", line 133, in <module>
    pd.DataFrame(outputs, colmuns=['date','avgR','stdR', 'avgS', 'stdS']).to_csv(obj+'.csv', index=False)
TypeError: __init__() got an unexpected keyword argument 'colmuns'
Traceback (most recent call last):
  File "/home/hongyuan/trader/backtest.py", line 133, in <module>
    pd.DataFrame(outputs, colmuns=['date','avgR','stdR', 'avgS', 'stdS']).to_csv(obj+'.csv', index=False)
TypeError: __init__() got an unexpected keyword argument 'colmuns'


















